services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fuelphp-app
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/html/my_fuel_project
    environment:
      - FUEL_ENV=development
